// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/pascalallen/go-clean-arch/internal/app/infrastructure/database"
	"github.com/pascalallen/go-clean-arch/internal/app/infrastructure/logger/slog"
	"github.com/pascalallen/go-clean-arch/internal/app/infrastructure/messaging"
	"github.com/pascalallen/go-clean-arch/internal/app/infrastructure/repository"
	"github.com/pascalallen/go-clean-arch/internal/app/infrastructure/websocket"
)

// Injectors from wire.go:

func InitializeContainer() Container {
	db := database.NewPostgresSession()
	logger := slog.New()
	permissionRepository := repository.NewPostgresPermissionRepository(db, logger)
	roleRepository := repository.NewPostgresRoleRepository(db, logger)
	userRepository := repository.NewPostgresUserRepository(db, logger)
	commandBus := messaging.NewChannelCommandBus(logger)
	queryBus := messaging.NewSynchronousQueryBus(logger)
	eventDispatcher := messaging.NewChannelEventDispatcher(logger)
	hub := websocket.NewHub()
	container := NewContainer(db, logger, permissionRepository, roleRepository, userRepository, commandBus, queryBus, eventDispatcher, hub)
	return container
}
